In [1]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import scipy as sp
import sympy as sy
sy.init_printing() 

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # display multiple results

In [3]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [5]:
A*B # this is Hadamard elementwise product

array([[ 5, 12],
       [21, 32]])

In [6]:
A@B # this is matrix product

array([[19, 22],
       [43, 50]])

In [7]:
np.sum(A[0,:]*B[:,0]) # (1, 1)
np.sum(A[1,:]*B[:,0]) # (2, 1)
np.sum(A[0,:]*B[:,1]) # (1, 2)
np.sum(A[1,:]*B[:,1]) # (2, 2)

19

43

22

50

In [8]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u,v, w, x, y, z')

In [9]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [10]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

In [11]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [12]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

In [13]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
A*B
B*A

⎡23  13⎤
⎢      ⎥
⎣51  29⎦

⎡36  44⎤
⎢      ⎥
⎣13  16⎦

In [14]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

In [15]:
M = A*B - B*A; M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

In [16]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d -a, -c], [0, c, -b, 0]]); A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

In [17]:
A_aug.rref()

⎛⎡        a   d    ⎤        ⎞
⎜⎢1  0  - ─ + ─  -1⎥        ⎟
⎜⎢        c   c    ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢        -b       ⎥        ⎟
⎜⎢0  1    ───    0 ⎥, (0, 1)⎟
⎜⎢         c       ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢0  0     0     0 ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎝⎣0  0     0     0 ⎦        ⎠

In [18]:
C = sy.Matrix([[1.1, .6], [1, 1]]);C

⎡1.1  0.6⎤
⎢        ⎥
⎣ 1    1 ⎦

In [19]:
A = sy.Matrix([[10, 12], [20, 8]])
A*C
C*A

⎡23.0  18.0⎤
⎢          ⎥
⎣30.0  20.0⎦

⎡23.0  18.0⎤
⎢          ⎥
⎣ 30    20 ⎦

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6]]); A
A.T # transpose

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]); A
A.transpose()

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

In [22]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB_tr = AB.transpose(); AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [23]:
B_tr_A_tr = B.transpose()*A.transpose()
B_tr_A_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [24]:
AB_tr - B_tr_A_tr

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

In [25]:
sy.eye(5)

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

In [26]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:

A = np.around(np.random.rand(5, 5)*100); A # generate a random matrix

array([[83., 71.,  1., 78., 14.],
       [ 7., 79., 79., 57., 29.],
       [75., 31., 45., 59., 80.],
       [ 7., 86., 61., 54., 98.],
       [54., 55., 45.,  6., 72.]])

In [28]:
A@I - I@A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
A = sy.randMatrix(3, percent = 80); A # generate a random matrix with 80% of entries being nonzero

⎡34  59  57⎤
⎢          ⎥
⎢34  46  0 ⎥
⎢          ⎥
⎣84  23  0 ⎦

In [30]:
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);E

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

In [31]:
E*A

⎡34  46  0 ⎤
⎢          ⎥
⎢34  59  57⎥
⎢          ⎥
⎣84  23  0 ⎦

In [32]:
A = sy.randMatrix(3, percent = 80); A
E = sy.Matrix([[1, 0, 0], [0, 1, 0], [-7, 0, 1]]); E

⎡67  98  0 ⎤
⎢          ⎥
⎢98  48  97⎥
⎢          ⎥
⎣26  0   50⎦

⎡1   0  0⎤
⎢        ⎥
⎢0   1  0⎥
⎢        ⎥
⎣-7  0  1⎦

In [33]:
EA = sy.matrices.MatrixBase.copy(A)
EA[2,:]=-7*EA[0,:]+EA[2,:]


In [34]:
A = np.round(10*np.random.randn(5,5)); A

array([[ -3.,  -1.,   5.,   3.,  -2.],
       [  3.,  20.,   8.,  -5.,  -4.],
       [ -1.,  -1.,  -5., -10., -14.],
       [ -6., -12.,  -5.,   8.,   1.],
       [ -0.,  14.,  -8.,  -4., -25.]])

In [35]:
Ainv = np.linalg.inv(A); Ainv

array([[ 0.11722555, -0.27323462, -0.13861531, -0.3387942 ,  0.0984123 ],
       [-0.08729935,  0.10942802,  0.00046669,  0.0982859 , -0.00685444],
       [ 0.16365104, -0.05366883, -0.00822533, -0.10728904, -0.00419045],
       [ 0.07337657, -0.08585068, -0.11098364, -0.06111635,  0.06757217],
       [-0.11299622,  0.09218982,  0.02065083,  0.09915122, -0.05330909]])

In [36]:
A@Ainv

array([[ 1.00000000e+00,  8.32667268e-17, -6.24500451e-17,
         2.22044605e-16, -6.93889390e-17],
       [-5.55111512e-17,  1.00000000e+00,  8.32667268e-17,
        -3.33066907e-16,  0.00000000e+00],
       [-1.38777878e-16,  2.77555756e-17,  1.00000000e+00,
         0.00000000e+00, -1.52655666e-16],
       [-1.38777878e-17, -2.08166817e-16, -7.28583860e-17,
         1.00000000e+00,  3.46944695e-17],
       [ 2.91433544e-16, -1.38777878e-17,  4.51028104e-17,
        -4.44089210e-16,  1.00000000e+00]])

In [37]:
AI = np.hstack((A, I)) # stack the matrix A and I horizontally
AI = sy.Matrix(AI); AI

⎡-3.0  -1.0   5.0    3.0   -2.0   1.0   0    0    0    0 ⎤
⎢                                                        ⎥
⎢3.0   20.0   8.0   -5.0   -4.0    0   1.0   0    0    0 ⎥
⎢                                                        ⎥
⎢-1.0  -1.0   -5.0  -10.0  -14.0   0    0   1.0   0    0 ⎥
⎢                                                        ⎥
⎢-6.0  -12.0  -5.0   8.0    1.0    0    0    0   1.0   0 ⎥
⎢                                                        ⎥
⎣ 0    14.0   -8.0  -4.0   -25.0   0    0    0    0   1.0⎦

In [38]:
AI_rref = AI.rref(); AI_rref

⎛⎡1  0  0  0  0   0.117225554918184   -0.273234616394271    -0.138615305338687
⎜⎢                                                                            
⎜⎢0  1  0  0  0  -0.0872993495571349   0.109428018628528   0.00046668546372006
⎜⎢                                                                            
⎜⎢0  0  1  0  0   0.163651035944503   -0.0536688283278076  -0.0082253312980661
⎜⎢                                                                            
⎜⎢0  0  0  1  0   0.073376566556153   -0.0858506800968372   -0.110983636840928
⎜⎢                                                                            
⎝⎣0  0  0  0  1  -0.112996217903221   0.0921898243123681    0.0206508317696129

   -0.338794201433113    0.098412297161969  ⎤                 ⎞
                                            ⎥                 ⎟
7  0.0982859031822115   -0.00685444274838848⎥                 ⎟
                                            ⎥                 ⎟
7  -0.107289043586478   -0.00419

In [39]:
Ainv = AI_rref[0][:,5:];Ainv # extract the RHS block

⎡ 0.117225554918184   -0.273234616394271    -0.138615305338687   -0.3387942014
⎢                                                                             
⎢-0.0872993495571349   0.109428018628528   0.000466685463720067  0.09828590318
⎢                                                                             
⎢ 0.163651035944503   -0.0536688283278076  -0.00822533129806617  -0.1072890435
⎢                                                                             
⎢ 0.073376566556153   -0.0858506800968372   -0.110983636840928   -0.0611163505
⎢                                                                             
⎣-0.112996217903221   0.0921898243123681    0.0206508317696129   0.09915121581

33113    0.098412297161969  ⎤
                            ⎥
22115   -0.00685444274838848⎥
                            ⎥
86478   -0.0041904465596531 ⎥
                            ⎥
196737   0.0675721661011346 ⎥
                            ⎥
28591   -0.0533090916161901 ⎦

In [40]:
round_expr(Ainv, 4) 

⎡0.1172   -0.2732  -0.1386  -0.3388  0.0984 ⎤
⎢                                           ⎥
⎢-0.0873  0.1094   0.0005   0.0983   -0.0069⎥
⎢                                           ⎥
⎢0.1637   -0.0537  -0.0082  -0.1073  -0.0042⎥
⎢                                           ⎥
⎢0.0734   -0.0859  -0.111   -0.0611  0.0676 ⎥
⎢                                           ⎥
⎣-0.113   0.0922   0.0207   0.0992   -0.0533⎦

In [41]:
A = sy.Matrix(A)
round_expr(A*Ainv, 4) 

⎡1.0   0    0    0    0 ⎤
⎢                       ⎥
⎢ 0   1.0   0    0    0 ⎥
⎢                       ⎥
⎢ 0    0   1.0   0    0 ⎥
⎢                       ⎥
⎢ 0    0    0   1.0   0 ⎥
⎢                       ⎥
⎣ 0    0    0    0   1.0⎦

In [42]:
lamb = sy.symbols('lamda') # SymPy will automatically render into LaTeX greek letters
A = np.array([[3, lamb, 1], [2, -1, 6], [1, 9, 4]])
I = np.eye(3); A

array([[3, lamda, 1],
       [2, -1, 6],
       [1, 9, 4]], dtype=object)

In [43]:
AI = np.hstack((A, I))
AI = sy.Matrix(AI); AI

⎡3  λ   1  1.0   0    0 ⎤
⎢                       ⎥
⎢2  -1  6   0   1.0   0 ⎥
⎢                       ⎥
⎣1  9   4   0    0   1.0⎦

In [44]:
AI_rref = AI.rref()
AI_rref

⎛⎡             116.0       8.0⋅λ - 18.0  -12.0⋅λ - 2.0⎤           ⎞
⎜⎢1  0  0  ─────────────  ─────────────  ─────────────⎥           ⎟
⎜⎢         4.0⋅λ + 310.0  4.0⋅λ + 310.0  4.0⋅λ + 310.0⎥           ⎟
⎜⎢                                                    ⎥           ⎟
⎜⎢              4.0           -22.0           32.0    ⎥           ⎟
⎜⎢0  1  0  ─────────────  ─────────────  ─────────────⎥, (0, 1, 2)⎟
⎜⎢         4.0⋅λ + 310.0  4.0⋅λ + 310.0  4.0⋅λ + 310.0⎥           ⎟
⎜⎢                                                    ⎥           ⎟
⎜⎢             57.0          27.0 - λ     2.0⋅λ + 3.0 ⎥           ⎟
⎜⎢0  0  1   ──────────    ─────────────  ─────────────⎥           ⎟
⎝⎣          -6⋅λ - 465    2.0⋅λ + 155.0  2.0⋅λ + 155.0⎦           ⎠

In [45]:
sy.solvers.solve(-6*lamb-465, lamb)

In [46]:

A = np.array([[3, -155/2, 1], [2, -1, 6], [1, 9, 4]])
np.linalg.det(A)